# Generated by Django 5.2.7 on 2025-11-24 11:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='story',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='default_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='duration',
            field=models.CharField(default='5 min', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
